### ISSUE TITLE
unable to understand. Issue with commands

### ISSUE THREAD

**Issue by Samrfengg** [DEMON1A/GmailBruterV2#10]
Unable to run few command or may be i am running it wrong. Can you please make the documentation more clear and also help me with this issue.

┌──(root💀kali)-[~/GmailBruterV2]
└─# python3 GmailBruterV2.py

                        [>] SimpleGMailBruter [<]

root@GmailBruter: help

Help Guide For GmailBruterV2.
Commands For Shell:
        help   --   To Show This Messages
        set target   --   To Set The Victim Email Address
        set time   --   To Set Time Between Every 10 Faild Passwords
        set list   --   To Set PassList Name 
        show target   --   To Show You Current Target 
        show time   --   To Show You Current Time 
        show list   --   To Show You Current List 
        load   --   Load Local Config For Settings
        start   --   To Start Brute Force Attack

        exit   --   Close The Shell
root@GmailBruter: s-set target email:007samabs@gmail.com
Command:set target email:007samabs@gmail.com
Results: 

root@GmailBruter: s-set list list=saurav.txt
Command:set list list=saurav.txt
Results: 

root@GmailBruter: s-set time time=10
Command:set time time=10
Results: 

root@GmailBruter: s-show target
/bin/sh: 1: show: not found
Command:show target
Results: 

root@GmailBruter: s-start
/bin/sh: 1: start: not found
Command:start
Results: 

root@GmailBruter:

**Comment by DEMON1A** [comment]
Hey @Samrfengg 

In GBv2, `s-command` is a shell command not GmailBruter command, so `s-python3` will start python3 shell anything after `s-` is a bash command that will get executed using `os.popen`

To set any value, for example the email do: `set target` then the shell will ask you for the email and it will set it on a variable to use it for the brute-force attack. don't add the email on the command or use `s-` on the command and it should work 

Please let me know if you need any help, and I would love if you can recommend an easier way to parse the command that will be easy for other users.

**Comment by DEMON1A** [comment]
Closing this issue, since there's no more comments to be added here.
